markdown: kramdown
pygments: true
paginate: 4

collections:
  posts:
    output: true
  gallery:
    output: true
  homePage:
    output: true
  projects:
    output: true
  resources:
    output: true
