markdown: kramdown
pygments: true
paginate: 4

collections:
  posts:
    output: true
  gallery:
    output: true
  homePage:
    output: true
  projects:
    output: true
  publications:
    output: true
  bookshelf:
    output: true
  tags:
    output: true
    permalink: tags/:path/